export default {
  token: null,
  employee_id: null,
  employee_full_name: null,
  employeeDeptCode: null,
  deptDescription: null,
  posDescription: null,
  has_work_experience: false,
  isOfficer: null,
  position: null,
  is_license: false,
  access_rights: {
    has_pis_access: false,
    is_pis_approver: false,
    is_leave_approver: false,
    facultyReportAccess: false,
    dutyRosterManage: false,
    dutyRosterCreate: false,
    dutyRosterView: false,
    employeeLeaveDetailsAccess: false,
    approverDetails: false,
    eventAccess: false,
    unpaidOvertime: false,
  },
};
