export default {
  leaveData: (state) => state.leaveData,
  leaveDetails: (state) => state.leaveDetails,
  pendingDetails: (state) => state.pendingDetails,
  balanceDetails: (state) => state.balanceDetails,
  leaveLedgerDetails: (state) => state.leaveLedgerDetails,
  userBalanceDetails: (state) => state.userBalanceDetails,
  base64Image: (state) => state.base64Image,
  approvedDetails: (state) => state.approvedDetails,
  rejectedDetails: (state) => state.rejectedDetails,
  getNumberOf403Errors: (state) => state.numberOf403Errors,
  userApprovedLeave: (state) => state.userApprovedLeave,
  userRejectedLeave: (state) => state.userRejectedLeave,
  cancelPending: (state) => state.cancelPending,
  approversDetails: (state) => state.approversDetails,
  userApprovedCancel: (state) => state.userApprovedCancel,
  userRejectedCancel: (state) => state.userRejectedCancel,
  rejectedCancel: (state) => state.rejectedCancel,
  approvedCancel: (state) => state.approvedCancel,
  leaveTypes: (state) => state.leaveTypes,
  empDetails: (state) => state.empDetails,
  appemp: (state) => state.appemp,
  allDept: (state) => state.allDept,
  selEmpByDept: (state) => state.selEmpByDept,
  getBgImage: (state) => state.base64Image,
};
