export default {
  leaveData: [],
  leaveDetails: [],
  pendingDetails: [],
  balanceDetails: [],
  userBalanceDetails: [],
  base64Image: null,
  approvedDetails: [],
  rejectedDetails: [],
  leaveLedgerDetails: [],
  numberOf403Errors: 0,
  userApprovedLeave: [],
  userRejectedLeave: [],
  cancelPending: [],
  approversDetails: [],
  userApprovedCancel: [],
  userRejectedCancel: [],
  rejectedCancel: [],
  approvedCancel: [],
  leaveTypes: [],
  empDetails: [],
  appemp: [],
  allDept: [],
  selEmpByDept: [],
};
